namespace CommonObj.Dashboard.Search.EFields;

public enum EFieldItemDeviceCamera
{
    ItemDeviceCameraid = 1,
    ItemDeviceCameraItemDeviceCameraDeviceCameradesignation = 4,
    ItemDeviceCameraitemsId = 5,
    ItemDeviceCameraitemtype = 6,
    ItemDeviceCameraInfocomimmoNumber = 25,
    ItemDeviceCameraInfocomorderNumber = 26,
    ItemDeviceCameraInfocomdeliveryNumber = 27,
    ItemDeviceCameraInfocombill = 28,
    ItemDeviceCameraContractItemContractname = 29,
    ItemDeviceCameraContractItemContractnum = 30,
    ItemDeviceCameraInfocombuyDate = 37,
    ItemDeviceCameraInfocomuseDate = 38,
    ItemDeviceCameraBudgetname = 50,
    ItemDeviceCameraInfocomwarrantyDuration = 51,
    ItemDeviceCameraInfocomwarrantyInfo = 52,
    ItemDeviceCameraSuppliername = 53,
    ItemDeviceCameraInfocomvalue = 54,
    ItemDeviceCameraInfocomwarrantyValue = 55,
    ItemDeviceCameraInfocomsinkTime = 56,
    ItemDeviceCameraInfocomsinkType = 57,
    ItemDeviceCameraInfocomsinkCoeff = 58,
    ItemDeviceCameraInfocomalert = 59,
    ItemDeviceCameraEntitycompletename = 80,
    ItemDeviceCameraDocumentItemid = 119,
    ItemDeviceCameraInfocomendWarranty = 120,
    ItemDeviceCameraInfocomcomment = 122,
    ItemDeviceCameraInfocomwarrantyDate = 123,
    ItemDeviceCameraInfocomorderDate = 124,
    ItemDeviceCameraInfocominventoryDate = 125,
    ItemDeviceCameraContractItemContractContractTypename = 129,
    ItemDeviceCameraContractItemContractduration = 130,
    ItemDeviceCameraContractItemContractperiodicity = 131,
    ItemDeviceCameraContractItemContractbeginDate = 132,
    ItemDeviceCameraContractItemContractaccountingNumber = 133,
    ItemDeviceCameraContractItemContractendDate = 134,
    ItemDeviceCameraContractItemContractnotice = 135,
    ItemDeviceCameraContractItemContractContractCosttotalcost = 136,
    ItemDeviceCameraContractItemContractbilling = 137,
    ItemDeviceCameraContractItemContractrenewal = 138,
    ItemDeviceCameraContractItemContractLocationcompletename = 139,
    ItemDeviceCameraInfocomdeliveryDate = 142,
    ItemDeviceCameraInfocomdecommissionDate = 159,
    ItemDeviceCameraBusinessCriticitycompletename = 173
}