namespace CommonObj.Dashboard.Search.EFields;

public enum EFieldAuthLdap
{
    AuthLdaPname = 1,
    AuthLdaPid = 2,
    AuthLdaPhost = 3,
    AuthLdaPport = 4,
    AuthLdaPbasedn = 5,
    AuthLdaPcondition = 6,
    AuthLdaPisDefault = 7,
    AuthLdaPloginField = 8,
    AuthLdaPrealnameField = 9,
    AuthLdaPfirstnameField = 10,
    AuthLdaPphoneField = 11,
    AuthLdaPphone2Field = 12,
    AuthLdaPmobileField = 13,
    AuthLdaPtitleField = 14,
    AuthLdaPcategoryField = 15,
    AuthLdaPcomment = 16,
    AuthLdaPemail1Field = 17,
    AuthLdaPuseDn = 18,
    AuthLdaPdateMod = 19,
    AuthLdaPlanguageField = 20,
    AuthLdaPgroupField = 21,
    AuthLdaPgroupCondition = 22,
    AuthLdaPgroupMemberField = 23,
    AuthLdaPgroupSearchType = 24,
    AuthLdaPemail2Field = 25,
    AuthLdaPemail3Field = 26,
    AuthLdaPemail4Field = 27,
    AuthLdaPsyncField = 28,
    AuthLdaPresponsibleField = 29,
    AuthLdaPisActive = 30,
    AuthLdaPinventoryDomain = 31,
    AuthLdaPtimeout = 32,
    AuthLdaPdateCreation = 121
}